### ISSUE TITLE
Access Not Configured. Google Cloud Deployment Manager API has not been used in project 1043443670838 beforeor it is disabled.

### ISSUE THREAD

**Issue by mrdulin** [mrdulin/nodejs-serverless-framework#2]
> Access Not Configured. Google Cloud Deployment Manager API has not been used in project 1043443670838 beforeor it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/deploymentmanager.googleapis.com/overview?project=1043443670838 then retry. If you enabled this API recently, wait a few minutes for the actionto propagate to our systems and retry.

出现该错误的原因是`serverless.yml`配置文件中的`project`字段指定的项目名称不对

```yml
provider:
  name: google
  runtime: nodejs
  project: my-project
  credentials: ~/workspace/nodejs-serverless-framework/.gcp/pg-gx-e-app-700458-98b46018b4ea.json
  environment:
    EMAIL_SERVICE_API_KEY: KEYEXAMPLE1234
```

`my-project`是一个在我的`GCP`上不存在的项目。修改后如下：

```yml
provider:
  name: google
  runtime: nodejs
  project: pg-gx-e-app-700458
  credentials: ~/workspace/nodejs-serverless-framework/.gcp/pg-gx-e-app-700458-98b46018b4ea.json
  environment:
    EMAIL_SERVICE_API_KEY: KEYEXAMPLE1234
```

参考:
https://github.com/serverless/serverless-google-cloudfunctions/issues/91
